services:
  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony_network


  webserver:
    image: nginx:stable
    container_name: symfony_webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - symfony_network


  database:
      image: mysql:8.0
      container_name: symfony_db
      environment:
        PMA_HOST: symfony_db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - "3307:3306"
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - symfony_network


  adminer:
    image: adminer
    container_name: symfony_adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - database
    networks:
      - symfony_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: symfony_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database
    networks:
      - symfony_network


networks:
  symfony_network:
    driver: bridge


volumes:
  db_data:
